# Generated by Django 5.2.3 on 2025-07-04 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_block_user", "Блокировка пользователя"),
                    ("can_view_all_user_lists", "Просмотр всех пользователей"),
                ],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
