# flake8: noqa
# Generated by Django 4.2.2 on 2024-11-30 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["first_sending"],
                "permissions": [("set_is_active", "set is active")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="receivemail",
            options={
                "ordering": ["fio"],
                "permissions": [
                    ("can_blocking_client", "Может блокировать получателя")
                ],
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
    ]
