# Generated by Django 5.2.3 on 2025-07-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "ordering": ["first_sending"],
                "permissions": [
                    ("set_is_active", "set is active"),
                    ("can_block_mailing", "блокировка рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
