# Generated by Django 4.2.2 on 2024-12-02 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mailing", "0002_alter_mailing_options_alter_receivemail_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="receivemail",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="активность"),
        ),
        migrations.AddField(
            model_name="receivemail",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="укажите получателя рассылки",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Получатель",
            ),
        ),
    ]
