# Generated by Django 5.1.2 on 2024-12-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0006_attemptmailing_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_sending",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="first_sending",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата первой отправки"
            ),
        ),
    ]
