# Generated by Django 5.1.2 on 2024-12-09 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0007_alter_mailing_end_sending_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="client",
            field=models.ManyToManyField(
                blank=True, null=True, to="mailing.receivemail", verbose_name="Клиент"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(
                blank=True, default=True, null=True, verbose_name="активна"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mailings",
                to="mailing.message",
                verbose_name="Сообщение",
            ),
        ),
    ]
