# Generated by Django 5.1.2 on 2024-12-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0008_alter_mailing_client_alter_mailing_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="client",
            field=models.ManyToManyField(
                to="mailing.receivemail", verbose_name="Клиент"
            ),
        ),
    ]
